### ISSUE TITLE
Requests fail (probably because wrong key is being used for `Ocp-Apim-Subscription-Key`)

### ISSUE THREAD

**Issue by safts** [nationalbankofgreece/open-bank-python#2]
When trying to test the client with a simple `GET` request I got a 404 error. 

To ensure it was not a server problem I tried replaying the request from the web portal, which seemed to work fine. 

Next step was copying the request headers and replaying the request from another client (etc Postman) which also worked fine. 

Then I noticed that `Ocp-Apim-Subscription-Key` contained the value of my `NBG_PRIMARY_KEY`, whereas `nbg.py` uses `NBG_SECONDARY_KEY`. I am not sure whether they are both supposed to work the same way, but swapping my keys worked for me. If this is a bug I can fix it and create a pull request. 

Let me know.

**Comment by parisk** [comment]
@sergafts the NBG API is still in testing phase from what I know, so things might change in the process. I guess you have to ask some of the people at NBG for this.

At the time we created this library the `NBG_SECONDARY_KEY` was used for authentication.
